#pragma once
    
// place overrides here
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 10
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT
#define OLED_DISPLAY_128X64
#define OLED_TIMEOUT 10000
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 2
#define COMBO_COUNT 1
#define COMBO_TERM 100
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 300
#define LEADER_NO_TIMEOUT
// tap dance and retlated
#define TAPPING_TERM 175
#define RETRO_TAPPING
#define IGNORE_MOD_TAP_INTERRUPT

// custom
#define ENABLE_LAYER_LED
