F_CPU=8000000
BOOTLOADER=caterina
MOUSEKEY_ENABLE=yes
# media keys
EXTRAKEY_ENABLE=yes
TAP_DANCE_ENABLE=yes
USB_HID_ENABLE=yes
LTO_ENABLE=yes
EXTRAFLAGS += -flto
OLED_ENABLE=yes
MAGIC_ENABLE=yes

LEADER_ENABLE=no
SPACE_CADET_ENABLE=no
GRAVE_ESC_ENABLE=no
COMMAND_ENABLE=no
COMBO_ENABLE=no
CONSOLE_ENABLE=no
UNICODE_ENABLE=no
SWAP_HANDS_ENABLE=no
DYNAMIC_MACRO_ENABLE=no
KEY_OVERRIDE_ENABLE=no
TERMINAL_ENABLE=no
