F_CPU=8000000
BOOTLOADER=caterina
MOUSEKEY_ENABLE=no
# media keys
EXTRAKEY_ENABLE=yes
COMMAND_ENABLE=yes
COMBO_ENABLE=no
CONSOLE_ENABLE=no
LEADER_ENABLE=yes
DYNAMIC_MACRO_ENABLE=yes
KEY_OVERRIDE_ENABLE=yes
# AUDIO_ENABLE=yes
USB_HID_ENABLE=yes
LTO_ENABLE=yes
